import type { Company, VehicleType, Temperature } from '@/types'

export const dummyCompanies: Company[] = [
  // --- PREMIUM (3 records) ---
  {
    id: 'c001',
    name: '山田運輸株式会社',
    nameKana: 'ヤマダウンユカブシキガイシャ',
    nameInitials: 'YU',
    plan: 'premium',
    prefecture: '大阪府',
    city: '大阪市北区',
    address: '大阪府大阪市北区梅田1-1-1',
    lat: 34.7024,
    lng: 135.4959,
    established: 2002,
    employeeCount: '150〜200名',
    capital: '5,000万円',
    licenseNumber: '近運貨第001号',
    mainClients: '大手食品メーカー、EC事業者',
    logoColor: '#1A3A5C',
    vehicles: [
      { type: '軽貨物', count: 5, hasRefrigeration: false, hasWingBody: false },
      { type: '2t', count: 8, hasRefrigeration: true, hasWingBody: true },
      { type: '4t', count: 12, hasRefrigeration: true, hasWingBody: true },
      { type: '10t', count: 6, hasRefrigeration: true, hasWingBody: false },
    ],
    specialties: ['冷凍輸送', '食品物流', 'EC配送', '工場間輸送', '深夜対応'],
    coverageAreas: ['大阪府', '兵庫県', '京都府', '奈良県', '和歌山県', '滋賀県'],
    temperatures: ['常温', '冷蔵', '冷凍'],
    canHandleUrgent: true,
    operatingHours: '24時間対応',
    targetCustomer: 'both',
    isAvailable24h: true,
    isWeekendAvailable: true,
    rating: 4.8,
    reviewCount: 87,
    ratingBreakdown: {
      deliveryQuality: 4.9, responseSpeed: 4.7,
      priceValue: 4.5, communication: 4.8, overall: 4.8,
    },
    responseTimeHours: 1.2,
    successRate: 94,
    availableVehicleCount: 3,
    currentlyAvailable: true,
    photos: ['/dummy-images/vehicles/4t-wing.jpg', '/dummy-images/vehicles/10t-ref.jpg', '/dummy-images/companies/warehouse-1.jpg'],
    prText: '創業20年以上の実績を持つ関西最大級の冷凍・冷蔵輸送専門会社です。24時間365日対応可能な体制と、充実した車両ラインナップで、お客様の物流ニーズに柔軟に対応します。',
    priceRangeMin: 180,
    priceRangeMax: 280,
  },
  {
    id: 'c002',
    name: '東洋物流株式会社',
    nameKana: 'トウヨウブツリュウカブシキガイシャ',
    nameInitials: 'TL',
    plan: 'premium',
    prefecture: '東京都',
    city: '江東区',
    address: '東京都江東区辰巳1-2-3',
    lat: 35.6430,
    lng: 139.8100,
    established: 1998,
    employeeCount: '300〜400名',
    capital: '1億円',
    licenseNumber: '関東貨第002号',
    mainClients: '大手小売、製造業各社',
    logoColor: '#1A5C3A',
    vehicles: [
      { type: '2t', count: 15, hasRefrigeration: true, hasWingBody: true },
      { type: '4t', count: 20, hasRefrigeration: true, hasWingBody: true },
      { type: '10t', count: 10, hasRefrigeration: false, hasWingBody: true },
    ],
    specialties: ['チルド輸送', '医薬品', '定温管理', '長距離輸送'],
    coverageAreas: ['東京都', '神奈川県', '埼玉県', '千葉県', '茨城県'],
    temperatures: ['常温', '冷蔵'],
    canHandleUrgent: true,
    operatingHours: '8:00〜22:00',
    targetCustomer: 'B2B',
    isAvailable24h: false,
    isWeekendAvailable: false,
    rating: 4.5,
    reviewCount: 63,
    ratingBreakdown: {
      deliveryQuality: 4.6, responseSpeed: 4.2,
      priceValue: 4.4, communication: 4.5, overall: 4.5,
    },
    responseTimeHours: 2.1,
    successRate: 88,
    availableVehicleCount: 0,
    currentlyAvailable: false,
    photos: ['/dummy-images/vehicles/2t-ref.jpg', '/dummy-images/companies/warehouse-2.jpg'],
    prText: '首都圏を中心に医薬品・食品の定温輸送に強みを持つ会社です。HACCP対応の専用車両と訓練されたドライバーで高品質な輸送サービスを提供します。',
    priceRangeMin: 200,
    priceRangeMax: 320,
  },
  {
    id: 'c003',
    name: '関西ロジスティクス株式会社',
    nameKana: 'カンサイロジスティクスカブシキガイシャ',
    nameInitials: 'KL',
    plan: 'premium',
    prefecture: '兵庫県',
    city: '神戸市中央区',
    address: '兵庫県神戸市中央区港島1-5-1',
    lat: 34.6750,
    lng: 135.2100,
    established: 2005,
    employeeCount: '80〜120名',
    capital: '3,000万円',
    licenseNumber: '近運貨第003号',
    mainClients: 'EC事業者、アパレルメーカー',
    logoColor: '#5C1A3A',
    vehicles: [
      { type: '軽貨物', count: 20, hasRefrigeration: false, hasWingBody: false },
      { type: '2t', count: 10, hasRefrigeration: false, hasWingBody: true },
      { type: '4t', count: 5, hasRefrigeration: false, hasWingBody: true },
    ],
    specialties: ['EC配送', '軽貨物', 'ラストワンマイル', '個人宅配送'],
    coverageAreas: ['兵庫県', '大阪府', '京都府'],
    temperatures: ['常温'],
    canHandleUrgent: true,
    operatingHours: '7:00〜21:00',
    targetCustomer: 'both',
    isAvailable24h: false,
    isWeekendAvailable: true,
    rating: 4.3,
    reviewCount: 41,
    ratingBreakdown: {
      deliveryQuality: 4.2, responseSpeed: 4.5,
      priceValue: 4.6, communication: 4.3, overall: 4.3,
    },
    responseTimeHours: 0.8,
    successRate: 91,
    availableVehicleCount: 5,
    currentlyAvailable: true,
    photos: ['/dummy-images/vehicles/kei.jpg'],
    prText: 'EC専門の軽貨物・小口配送に特化した会社です。当日・翌日配送体制で関西圏全域をカバーします。',
    priceRangeMin: 120,
    priceRangeMax: 200,
  },

  // --- STANDARD (13 records) ---
  {
    id: 'c004',
    name: '中部輸送株式会社',
    nameKana: 'チュウブユソウカブシキガイシャ',
    nameInitials: 'CY',
    plan: 'standard',
    prefecture: '愛知県',
    city: '名古屋市西区',
    address: '愛知県名古屋市西区名駅2-2-2',
    lat: 35.1709,
    lng: 136.8815,
    established: 2010,
    employeeCount: '50〜80名',
    capital: '2,000万円',
    licenseNumber: '中部貨第004号',
    mainClients: '自動車部品メーカー',
    logoColor: '#1A5C5C',
    vehicles: [
      { type: '2t', count: 6, hasRefrigeration: false, hasWingBody: true },
      { type: '4t', count: 8, hasRefrigeration: false, hasWingBody: true },
      { type: '10t', count: 4, hasRefrigeration: false, hasWingBody: false },
    ],
    specialties: ['工場間輸送', '自動車部品', '定期便', '精密機器'],
    coverageAreas: ['愛知県', '三重県', '岐阜県', '静岡県'],
    temperatures: ['常温'],
    canHandleUrgent: false,
    operatingHours: '9:00〜18:00',
    targetCustomer: 'B2B',
    isAvailable24h: false,
    isWeekendAvailable: false,
    rating: 4.1,
    reviewCount: 28,
    ratingBreakdown: {
      deliveryQuality: 4.2, responseSpeed: 3.8,
      priceValue: 4.3, communication: 4.0, overall: 4.1,
    },
    responseTimeHours: 3.5,
    successRate: 82,
    availableVehicleCount: 2,
    currentlyAvailable: true,
    photos: ['/dummy-images/vehicles/4t-flat.jpg'],
    prText: '中部圏の工場間輸送を専門とした運送会社です。',
    priceRangeMin: 160,
    priceRangeMax: 240,
  },
  {
    id: 'c005',
    name: '北九州運送株式会社',
    nameKana: 'キタキュウシュウウンソウカブシキガイシャ',
    nameInitials: 'KU',
    plan: 'standard',
    prefecture: '福岡県',
    city: '北九州市小倉北区',
    address: '福岡県北九州市小倉北区浅野1-1-1',
    lat: 33.8835,
    lng: 130.8752,
    established: 2008,
    employeeCount: '40〜60名',
    capital: '1,500万円',
    licenseNumber: '九州貨第005号',
    mainClients: '食品卸、小売チェーン',
    logoColor: '#5C3A1A',
    vehicles: [
      { type: '2t', count: 10, hasRefrigeration: true, hasWingBody: false },
      { type: '4t', count: 6, hasRefrigeration: true, hasWingBody: false },
    ],
    specialties: ['食品輸送', '冷蔵便', '九州全域'],
    coverageAreas: ['福岡県', '佐賀県', '長崎県', '大分県', '熊本県', '鹿児島県'],
    temperatures: ['常温', '冷蔵'],
    canHandleUrgent: true,
    operatingHours: '6:00〜22:00',
    targetCustomer: 'B2B',
    isAvailable24h: false,
    isWeekendAvailable: true,
    rating: 4.0,
    reviewCount: 19,
    ratingBreakdown: {
      deliveryQuality: 4.1, responseSpeed: 4.2,
      priceValue: 4.0, communication: 3.9, overall: 4.0,
    },
    responseTimeHours: 1.8,
    successRate: 85,
    availableVehicleCount: 1,
    currentlyAvailable: true,
    photos: ['/dummy-images/vehicles/2t-ref.jpg'],
    prText: '九州全域を網羅する食品特化の冷蔵輸送会社です。',
    priceRangeMin: 150,
    priceRangeMax: 230,
  },
  {
    id: 'c006',
    name: '東北ロジテック株式会社',
    nameKana: 'トウホクロジテックカブシキガイシャ',
    nameInitials: 'TJ',
    plan: 'standard',
    prefecture: '宮城県',
    city: '仙台市青葉区',
    address: '宮城県仙台市青葉区中央1-3-1',
    lat: 38.2601,
    lng: 140.8820,
    established: 2012,
    employeeCount: '30〜50名',
    capital: '1,000万円',
    licenseNumber: '東北貨第006号',
    mainClients: '農産物生産者、水産加工会社',
    logoColor: '#3A5C1A',
    vehicles: [
      { type: '2t', count: 8, hasRefrigeration: true, hasWingBody: false },
      { type: '4t', count: 4, hasRefrigeration: true, hasWingBody: true },
    ],
    specialties: ['農産物輸送', '水産物', '冷凍便', '東北全域'],
    coverageAreas: ['宮城県', '岩手県', '秋田県', '山形県', '福島県'],
    temperatures: ['常温', '冷蔵', '冷凍'],
    canHandleUrgent: false,
    operatingHours: '7:00〜19:00',
    targetCustomer: 'B2B',
    isAvailable24h: false,
    isWeekendAvailable: false,
    rating: 4.2,
    reviewCount: 22,
    ratingBreakdown: {
      deliveryQuality: 4.3, responseSpeed: 4.0,
      priceValue: 4.4, communication: 4.1, overall: 4.2,
    },
    responseTimeHours: 2.5,
    successRate: 86,
    availableVehicleCount: 2,
    currentlyAvailable: true,
    photos: ['/dummy-images/vehicles/4t-wing.jpg'],
    prText: '東北の農産物・水産物輸送のエキスパートです。',
    priceRangeMin: 140,
    priceRangeMax: 220,
  },
  {
    id: 'c007',
    name: '首都圏エクスプレス株式会社',
    nameKana: 'シュトケンエクスプレスカブシキガイシャ',
    nameInitials: 'SE',
    plan: 'standard',
    prefecture: '東京都',
    city: '品川区',
    address: '東京都品川区東品川2-5-8',
    lat: 35.6216,
    lng: 139.7480,
    established: 2015,
    employeeCount: '20〜30名',
    capital: '800万円',
    licenseNumber: '関東貨第007号',
    mainClients: 'EC事業者、通販会社',
    logoColor: '#5C1A5C',
    vehicles: [
      { type: '軽貨物', count: 15, hasRefrigeration: false, hasWingBody: false },
      { type: '2t', count: 5, hasRefrigeration: false, hasWingBody: false },
    ],
    specialties: ['当日配送', 'EC物流', '軽貨物', '都内配送'],
    coverageAreas: ['東京都', '神奈川県', '埼玉県'],
    temperatures: ['常温'],
    canHandleUrgent: true,
    operatingHours: '8:00〜21:00',
    targetCustomer: 'B2C',
    isAvailable24h: false,
    isWeekendAvailable: true,
    rating: 3.9,
    reviewCount: 15,
    ratingBreakdown: {
      deliveryQuality: 3.8, responseSpeed: 4.3,
      priceValue: 4.0, communication: 3.8, overall: 3.9,
    },
    responseTimeHours: 0.5,
    successRate: 90,
    availableVehicleCount: 4,
    currentlyAvailable: true,
    photos: ['/dummy-images/vehicles/kei.jpg'],
    prText: '首都圏に特化した当日配送サービスを提供します。',
    priceRangeMin: 100,
    priceRangeMax: 180,
  },
  {
    id: 'c008',
    name: '北海道物流センター株式会社',
    nameKana: 'ホッカイドウブツリュウセンターカブシキガイシャ',
    nameInitials: 'HC',
    plan: 'standard',
    prefecture: '北海道',
    city: '札幌市白石区',
    address: '北海道札幌市白石区流通センター1-1',
    lat: 43.0389,
    lng: 141.3903,
    established: 2001,
    employeeCount: '60〜90名',
    capital: '3,000万円',
    licenseNumber: '北海道貨第008号',
    mainClients: '乳製品メーカー、海産物卸',
    logoColor: '#1A3A5C',
    vehicles: [
      { type: '4t', count: 10, hasRefrigeration: true, hasWingBody: true },
      { type: '10t', count: 8, hasRefrigeration: true, hasWingBody: false },
    ],
    specialties: ['乳製品輸送', '海産物', '冷凍長距離', '北海道全域'],
    coverageAreas: ['北海道'],
    temperatures: ['常温', '冷蔵', '冷凍'],
    canHandleUrgent: false,
    operatingHours: '6:00〜20:00',
    targetCustomer: 'B2B',
    isAvailable24h: false,
    isWeekendAvailable: false,
    rating: 4.4,
    reviewCount: 35,
    ratingBreakdown: {
      deliveryQuality: 4.5, responseSpeed: 4.1,
      priceValue: 4.3, communication: 4.4, overall: 4.4,
    },
    responseTimeHours: 3.0,
    successRate: 87,
    availableVehicleCount: 3,
    currentlyAvailable: true,
    photos: ['/dummy-images/vehicles/10t-ref.jpg'],
    prText: '北海道の乳製品・海産物輸送のスペシャリストです。',
    priceRangeMin: 170,
    priceRangeMax: 260,
  },
  {
    id: 'c009',
    name: '四国運輸株式会社',
    nameKana: 'シコクウンユカブシキガイシャ',
    nameInitials: 'SU',
    plan: 'standard',
    prefecture: '香川県',
    city: '高松市',
    address: '香川県高松市浜ノ町1-20',
    lat: 34.3500,
    lng: 134.0467,
    established: 2009,
    employeeCount: '25〜40名',
    capital: '1,200万円',
    licenseNumber: '四国貨第009号',
    mainClients: '食品加工会社、農協',
    logoColor: '#3A1A5C',
    vehicles: [
      { type: '2t', count: 6, hasRefrigeration: true, hasWingBody: false },
      { type: '4t', count: 4, hasRefrigeration: false, hasWingBody: true },
    ],
    specialties: ['四国全域', '農産物', '食品配送'],
    coverageAreas: ['香川県', '徳島県', '愛媛県', '高知県'],
    temperatures: ['常温', '冷蔵'],
    canHandleUrgent: false,
    operatingHours: '8:00〜18:00',
    targetCustomer: 'B2B',
    isAvailable24h: false,
    isWeekendAvailable: false,
    rating: 3.8,
    reviewCount: 12,
    ratingBreakdown: {
      deliveryQuality: 3.9, responseSpeed: 3.6,
      priceValue: 4.1, communication: 3.7, overall: 3.8,
    },
    responseTimeHours: 4.0,
    successRate: 79,
    availableVehicleCount: 1,
    currentlyAvailable: true,
    photos: [],
    prText: '四国4県をカバーする地域密着型運送会社です。',
    priceRangeMin: 130,
    priceRangeMax: 210,
  },
  {
    id: 'c010',
    name: '横浜港運株式会社',
    nameKana: 'ヨコハマコウウンカブシキガイシャ',
    nameInitials: 'YK',
    plan: 'standard',
    prefecture: '神奈川県',
    city: '横浜市中区',
    address: '神奈川県横浜市中区海岸通1-1',
    lat: 35.4437,
    lng: 139.6380,
    established: 1995,
    employeeCount: '100〜150名',
    capital: '8,000万円',
    licenseNumber: '関東貨第010号',
    mainClients: '輸入商社、メーカー各社',
    logoColor: '#1A5C1A',
    vehicles: [
      { type: '4t', count: 15, hasRefrigeration: false, hasWingBody: true },
      { type: '10t', count: 12, hasRefrigeration: false, hasWingBody: true },
    ],
    specialties: ['港湾輸送', 'コンテナ', '倉庫保管', '通関連携'],
    coverageAreas: ['神奈川県', '東京都', '千葉県'],
    temperatures: ['常温'],
    canHandleUrgent: true,
    operatingHours: '24時間対応',
    targetCustomer: 'B2B',
    isAvailable24h: true,
    isWeekendAvailable: true,
    rating: 4.0,
    reviewCount: 45,
    ratingBreakdown: {
      deliveryQuality: 4.0, responseSpeed: 3.9,
      priceValue: 3.8, communication: 4.1, overall: 4.0,
    },
    responseTimeHours: 2.0,
    successRate: 83,
    availableVehicleCount: 0,
    currentlyAvailable: false,
    photos: ['/dummy-images/companies/warehouse-1.jpg'],
    prText: '横浜港を拠点とした港湾物流の老舗企業です。',
    priceRangeMin: 190,
    priceRangeMax: 300,
  },
  {
    id: 'c011',
    name: '信州フレッシュ便株式会社',
    nameKana: 'シンシュウフレッシュビンカブシキガイシャ',
    nameInitials: 'SF',
    plan: 'standard',
    prefecture: '長野県',
    city: '松本市',
    address: '長野県松本市渚1-7-1',
    lat: 36.2309,
    lng: 137.9720,
    established: 2014,
    employeeCount: '15〜25名',
    capital: '600万円',
    licenseNumber: '中部貨第011号',
    mainClients: '高原野菜生産者、ワイナリー',
    logoColor: '#5C5C1A',
    vehicles: [
      { type: '2t', count: 4, hasRefrigeration: true, hasWingBody: false },
      { type: '4t', count: 3, hasRefrigeration: true, hasWingBody: false },
    ],
    specialties: ['高原野菜', '冷蔵輸送', 'ワイン配送', '信州エリア'],
    coverageAreas: ['長野県', '山梨県', '新潟県'],
    temperatures: ['常温', '冷蔵'],
    canHandleUrgent: false,
    operatingHours: '5:00〜17:00',
    targetCustomer: 'B2B',
    isAvailable24h: false,
    isWeekendAvailable: false,
    rating: 4.6,
    reviewCount: 18,
    ratingBreakdown: {
      deliveryQuality: 4.7, responseSpeed: 4.3,
      priceValue: 4.5, communication: 4.6, overall: 4.6,
    },
    responseTimeHours: 2.8,
    successRate: 92,
    availableVehicleCount: 1,
    currentlyAvailable: true,
    photos: ['/dummy-images/vehicles/2t-ref.jpg'],
    prText: '信州の新鮮な農産物を朝採れで首都圏へお届けします。',
    priceRangeMin: 150,
    priceRangeMax: 230,
  },
  {
    id: 'c012',
    name: '広島急送株式会社',
    nameKana: 'ヒロシマキュウソウカブシキガイシャ',
    nameInitials: 'HK',
    plan: 'standard',
    prefecture: '広島県',
    city: '広島市南区',
    address: '広島県広島市南区宇品海岸1-13',
    lat: 34.3667,
    lng: 132.4750,
    established: 2007,
    employeeCount: '35〜55名',
    capital: '1,800万円',
    licenseNumber: '中国貨第012号',
    mainClients: '自動車関連、鉄鋼メーカー',
    logoColor: '#5C1A1A',
    vehicles: [
      { type: '4t', count: 7, hasRefrigeration: false, hasWingBody: true },
      { type: '10t', count: 5, hasRefrigeration: false, hasWingBody: false },
    ],
    specialties: ['重量物', '鉄鋼輸送', '中国地方全域'],
    coverageAreas: ['広島県', '岡山県', '山口県', '島根県', '鳥取県'],
    temperatures: ['常温'],
    canHandleUrgent: true,
    operatingHours: '7:00〜20:00',
    targetCustomer: 'B2B',
    isAvailable24h: false,
    isWeekendAvailable: false,
    rating: 3.7,
    reviewCount: 14,
    ratingBreakdown: {
      deliveryQuality: 3.8, responseSpeed: 3.6,
      priceValue: 3.9, communication: 3.5, overall: 3.7,
    },
    responseTimeHours: 3.2,
    successRate: 78,
    availableVehicleCount: 2,
    currentlyAvailable: true,
    photos: ['/dummy-images/vehicles/10t-ref.jpg'],
    prText: '中国地方の重量物・鉄鋼輸送を得意とする会社です。',
    priceRangeMin: 170,
    priceRangeMax: 270,
  },
  {
    id: 'c013',
    name: '沖縄ロジサポート株式会社',
    nameKana: 'オキナワロジサポートカブシキガイシャ',
    nameInitials: 'OL',
    plan: 'standard',
    prefecture: '沖縄県',
    city: '那覇市',
    address: '沖縄県那覇市港町2-16',
    lat: 26.2124,
    lng: 127.6792,
    established: 2016,
    employeeCount: '10〜20名',
    capital: '500万円',
    licenseNumber: '沖縄貨第013号',
    mainClients: '観光業者、飲食チェーン',
    logoColor: '#1A5C5C',
    vehicles: [
      { type: '軽貨物', count: 8, hasRefrigeration: false, hasWingBody: false },
      { type: '2t', count: 4, hasRefrigeration: true, hasWingBody: false },
    ],
    specialties: ['島内配送', '飲食店配送', '冷蔵小口'],
    coverageAreas: ['沖縄県'],
    temperatures: ['常温', '冷蔵'],
    canHandleUrgent: true,
    operatingHours: '7:00〜21:00',
    targetCustomer: 'both',
    isAvailable24h: false,
    isWeekendAvailable: true,
    rating: 4.1,
    reviewCount: 9,
    ratingBreakdown: {
      deliveryQuality: 4.0, responseSpeed: 4.3,
      priceValue: 4.2, communication: 4.0, overall: 4.1,
    },
    responseTimeHours: 1.0,
    successRate: 88,
    availableVehicleCount: 3,
    currentlyAvailable: true,
    photos: [],
    prText: '沖縄本島内の配送をスピーディーにサポートします。',
    priceRangeMin: 110,
    priceRangeMax: 190,
  },

  // --- FREE (4 records) ---
  {
    id: 'c014',
    name: '田中物流',
    nameKana: 'タナカブツリュウ',
    nameInitials: 'TB',
    plan: 'free',
    prefecture: '埼玉県',
    city: 'さいたま市大宮区',
    address: '埼玉県さいたま市大宮区大門町1-1',
    lat: 35.9060,
    lng: 139.6238,
    established: 2018,
    employeeCount: '5〜15名',
    capital: '500万円',
    licenseNumber: '関東貨第014号',
    mainClients: '個人・中小企業',
    logoColor: '#3A3A5C',
    vehicles: [
      { type: '軽貨物', count: 3, hasRefrigeration: false, hasWingBody: false },
      { type: '2t', count: 2, hasRefrigeration: false, hasWingBody: false },
    ],
    specialties: ['一般貨物', '引越し補助'],
    coverageAreas: ['埼玉県', '東京都'],
    temperatures: ['常温'],
    canHandleUrgent: false,
    operatingHours: '9:00〜18:00',
    targetCustomer: 'B2C',
    isAvailable24h: false,
    isWeekendAvailable: false,
    rating: 3.8,
    reviewCount: 7,
    ratingBreakdown: {
      deliveryQuality: 3.8, responseSpeed: 3.5,
      priceValue: 4.2, communication: 3.7, overall: 3.8,
    },
    responseTimeHours: 6.0,
    successRate: 70,
    availableVehicleCount: 0,
    currentlyAvailable: false,
    photos: [],
    prText: '小回りの効く地域密着型の運送会社です。',
    priceRangeMin: 100,
    priceRangeMax: 180,
  },
  {
    id: 'c015',
    name: '佐藤運送',
    nameKana: 'サトウウンソウ',
    nameInitials: 'SU',
    plan: 'free',
    prefecture: '千葉県',
    city: '船橋市',
    address: '千葉県船橋市湊町2-3',
    lat: 35.6948,
    lng: 139.9827,
    established: 2020,
    employeeCount: '3〜10名',
    capital: '300万円',
    licenseNumber: '関東貨第015号',
    mainClients: '個人事業主',
    logoColor: '#5C5C3A',
    vehicles: [
      { type: '軽貨物', count: 5, hasRefrigeration: false, hasWingBody: false },
    ],
    specialties: ['軽貨物', '個人宅配送'],
    coverageAreas: ['千葉県', '東京都'],
    temperatures: ['常温'],
    canHandleUrgent: false,
    operatingHours: '10:00〜18:00',
    targetCustomer: 'B2C',
    isAvailable24h: false,
    isWeekendAvailable: false,
    rating: 3.5,
    reviewCount: 4,
    ratingBreakdown: {
      deliveryQuality: 3.5, responseSpeed: 3.3,
      priceValue: 4.0, communication: 3.4, overall: 3.5,
    },
    responseTimeHours: 8.0,
    successRate: 65,
    availableVehicleCount: 1,
    currentlyAvailable: true,
    photos: [],
    prText: '軽貨物メインの小規模運送です。',
    priceRangeMin: 80,
    priceRangeMax: 150,
  },
  {
    id: 'c016',
    name: '鈴木配送サービス',
    nameKana: 'スズキハイソウサービス',
    nameInitials: 'SH',
    plan: 'free',
    prefecture: '京都府',
    city: '京都市下京区',
    address: '京都府京都市下京区四条通1-1',
    lat: 34.9960,
    lng: 135.7590,
    established: 2019,
    employeeCount: '5〜10名',
    capital: '400万円',
    licenseNumber: '近運貨第016号',
    mainClients: '和菓子店、料亭',
    logoColor: '#3A5C5C',
    vehicles: [
      { type: '軽貨物', count: 4, hasRefrigeration: true, hasWingBody: false },
      { type: '2t', count: 1, hasRefrigeration: true, hasWingBody: false },
    ],
    specialties: ['食品小口', '京都市内'],
    coverageAreas: ['京都府', '大阪府'],
    temperatures: ['常温', '冷蔵'],
    canHandleUrgent: true,
    operatingHours: '6:00〜15:00',
    targetCustomer: 'B2C',
    isAvailable24h: false,
    isWeekendAvailable: false,
    rating: 4.0,
    reviewCount: 6,
    ratingBreakdown: {
      deliveryQuality: 4.1, responseSpeed: 4.0,
      priceValue: 4.2, communication: 3.8, overall: 4.0,
    },
    responseTimeHours: 1.5,
    successRate: 80,
    availableVehicleCount: 2,
    currentlyAvailable: true,
    photos: [],
    prText: '京都の和菓子・食品をていねいにお届けします。',
    priceRangeMin: 90,
    priceRangeMax: 160,
  },
  {
    id: 'c017',
    name: '高橋トランスポート',
    nameKana: 'タカハシトランスポート',
    nameInitials: 'TT',
    plan: 'free',
    prefecture: '福岡県',
    city: '福岡市博多区',
    address: '福岡県福岡市博多区博多駅南3-1',
    lat: 33.5845,
    lng: 130.4181,
    established: 2021,
    employeeCount: '3〜8名',
    capital: '200万円',
    licenseNumber: '九州貨第017号',
    mainClients: '中小企業、個人',
    logoColor: '#5C3A3A',
    vehicles: [
      { type: '軽貨物', count: 3, hasRefrigeration: false, hasWingBody: false },
      { type: '2t', count: 1, hasRefrigeration: false, hasWingBody: false },
    ],
    specialties: ['一般貨物', '福岡市内'],
    coverageAreas: ['福岡県'],
    temperatures: ['常温'],
    canHandleUrgent: false,
    operatingHours: '9:00〜17:00',
    targetCustomer: 'B2C',
    isAvailable24h: false,
    isWeekendAvailable: false,
    rating: 3.6,
    reviewCount: 3,
    ratingBreakdown: {
      deliveryQuality: 3.7, responseSpeed: 3.4,
      priceValue: 3.8, communication: 3.5, overall: 3.6,
    },
    responseTimeHours: 5.0,
    successRate: 72,
    availableVehicleCount: 0,
    currentlyAvailable: false,
    photos: [],
    prText: '福岡市内の小口配送を承ります。',
    priceRangeMin: 90,
    priceRangeMax: 160,
  },
]

export function getCompanyById(id: string): Company | undefined {
  return dummyCompanies.find(c => c.id === id)
}

export function searchCompanies(params: {
  prefecture?: string
  vehicleType?: VehicleType
  temperature?: Temperature
  urgentOnly?: boolean
  minVehicleCount?: number
  targetCustomer?: 'B2B' | 'B2C'
  availableHours?: '24h' | 'weekend'
}): Company[] {
  return dummyCompanies.filter(c => {
    if (params.prefecture && !c.coverageAreas.includes(params.prefecture)) return false
    if (params.vehicleType && !c.vehicles.some(v => v.type === params.vehicleType)) return false
    if (params.temperature && !c.temperatures.includes(params.temperature)) return false
    if (params.urgentOnly && !c.canHandleUrgent) return false
    if (params.minVehicleCount && c.vehicles.reduce((s, v) => s + v.count, 0) < params.minVehicleCount) return false
    if (params.targetCustomer && c.targetCustomer !== params.targetCustomer && c.targetCustomer !== 'both') return false
    if (params.availableHours === '24h' && !c.isAvailable24h) return false
    if (params.availableHours === 'weekend' && !c.isWeekendAvailable) return false
    return true
  })
}
