import type { Job } from '@/types'

export const dummyJobs: Job[] = [
  // === Premium: c001 山田運輸 (大阪府) — 4 jobs ===
  {
    id: 'j001',
    companyId: 'c001',
    title: '4tドライバー／大阪市内ルート配送',
    employmentType: '正社員',
    salaryMin: 300000,
    salaryMax: 380000,
    salaryType: '月給',
    location: '大阪府大阪市住之江区',
    requiredLicense: '中型免許',
    vehicleType: '4t',
    isActive: true,
    postedAt: '2025-11-01',
  },
  {
    id: 'j002',
    companyId: 'c001',
    title: '10t長距離ドライバー／大阪⇔東京便',
    employmentType: '正社員',
    salaryMin: 350000,
    salaryMax: 450000,
    salaryType: '月給',
    location: '大阪府大阪市住之江区',
    requiredLicense: '大型免許',
    vehicleType: '10t',
    isActive: true,
    postedAt: '2025-12-15',
  },
  {
    id: 'j003',
    companyId: 'c001',
    title: '軽貨物ドライバー／宅配便ラストワンマイル',
    employmentType: '業務委託',
    salaryMin: 13000,
    salaryMax: 18000,
    salaryType: '日給',
    location: '大阪府堺市',
    requiredLicense: '普通免許',
    vehicleType: '軽貨物',
    isActive: true,
    postedAt: '2026-01-10',
  },
  {
    id: 'j004',
    companyId: 'c001',
    title: '倉庫内仕分け・積込みスタッフ',
    employmentType: 'アルバイト',
    salaryMin: 1200,
    salaryMax: 1500,
    salaryType: '時給',
    location: '大阪府大阪市住之江区',
    requiredLicense: '不要',
    vehicleType: '軽貨物',
    isActive: false,
    postedAt: '2025-08-20',
  },

  // === Premium: c002 東洋物流 (東京都) — 4 jobs ===
  {
    id: 'j005',
    companyId: 'c002',
    title: '2tドライバー／都内企業配送',
    employmentType: '正社員',
    salaryMin: 280000,
    salaryMax: 350000,
    salaryType: '月給',
    location: '東京都江東区',
    requiredLicense: '準中型免許',
    vehicleType: '2t',
    isActive: true,
    postedAt: '2025-10-05',
  },
  {
    id: 'j006',
    companyId: 'c002',
    title: '4t冷蔵車ドライバー／食品配送',
    employmentType: '正社員',
    salaryMin: 320000,
    salaryMax: 400000,
    salaryType: '月給',
    location: '東京都江東区',
    requiredLicense: '中型免許',
    vehicleType: '4t',
    isActive: true,
    postedAt: '2026-02-01',
  },
  {
    id: 'j007',
    companyId: 'c002',
    title: '10tウイング車ドライバー／関東圏幹線輸送',
    employmentType: '正社員',
    salaryMin: 380000,
    salaryMax: 450000,
    salaryType: '月給',
    location: '東京都江東区',
    requiredLicense: '大型免許',
    vehicleType: '10t',
    isActive: true,
    postedAt: '2026-01-20',
  },
  {
    id: 'j008',
    companyId: 'c002',
    title: '軽貨物配送パートナー／EC宅配',
    employmentType: '業務委託',
    salaryMin: 14000,
    salaryMax: 18000,
    salaryType: '日給',
    location: '東京都品川区',
    requiredLicense: '普通免許',
    vehicleType: '軽貨物',
    isActive: false,
    postedAt: '2025-07-15',
  },

  // === Premium: c003 関西ロジスティクス (兵庫県) — 3 jobs ===
  {
    id: 'j009',
    companyId: 'c003',
    title: '4tドライバー／神戸港コンテナ搬出入',
    employmentType: '正社員',
    salaryMin: 300000,
    salaryMax: 370000,
    salaryType: '月給',
    location: '兵庫県神戸市中央区',
    requiredLicense: '中型免許',
    vehicleType: '4t',
    isActive: true,
    postedAt: '2025-11-20',
  },
  {
    id: 'j010',
    companyId: 'c003',
    title: '10tドライバー／関西⇔九州定期便',
    employmentType: '正社員',
    salaryMin: 340000,
    salaryMax: 430000,
    salaryType: '月給',
    location: '兵庫県神戸市中央区',
    requiredLicense: '大型免許',
    vehicleType: '10t',
    isActive: true,
    postedAt: '2026-02-10',
  },
  {
    id: 'j011',
    companyId: 'c003',
    title: '2t冷凍車ドライバー／スーパー納品',
    employmentType: '契約社員',
    salaryMin: 270000,
    salaryMax: 330000,
    salaryType: '月給',
    location: '兵庫県尼崎市',
    requiredLicense: '準中型免許',
    vehicleType: '2t',
    isActive: true,
    postedAt: '2026-03-01',
  },

  // === Standard: c004 中部輸送 (愛知県) — 2 jobs ===
  {
    id: 'j012',
    companyId: 'c004',
    title: '4tドライバー／自動車部品輸送',
    employmentType: '正社員',
    salaryMin: 290000,
    salaryMax: 360000,
    salaryType: '月給',
    location: '愛知県名古屋市港区',
    requiredLicense: '中型免許',
    vehicleType: '4t',
    isActive: true,
    postedAt: '2025-12-01',
  },
  {
    id: 'j013',
    companyId: 'c004',
    title: '10tドライバー／東海⇔関東幹線便',
    employmentType: '正社員',
    salaryMin: 330000,
    salaryMax: 420000,
    salaryType: '月給',
    location: '愛知県名古屋市港区',
    requiredLicense: '大型免許',
    vehicleType: '10t',
    isActive: true,
    postedAt: '2026-01-05',
  },

  // === Standard: c005 北九州運送 (福岡県) — 2 jobs ===
  {
    id: 'j014',
    companyId: 'c005',
    title: '2tドライバー／福岡市内飲食店配送',
    employmentType: '正社員',
    salaryMin: 260000,
    salaryMax: 320000,
    salaryType: '月給',
    location: '福岡県北九州市門司区',
    requiredLicense: '準中型免許',
    vehicleType: '2t',
    isActive: true,
    postedAt: '2025-09-15',
  },
  {
    id: 'j015',
    companyId: 'c005',
    title: '軽貨物ドライバー／個人宅配送',
    employmentType: 'アルバイト',
    salaryMin: 1200,
    salaryMax: 1500,
    salaryType: '時給',
    location: '福岡県福岡市博多区',
    requiredLicense: '普通免許',
    vehicleType: '軽貨物',
    isActive: false,
    postedAt: '2025-06-10',
  },

  // === Standard: c006 東北ロジテック (宮城県) — 2 jobs ===
  {
    id: 'j016',
    companyId: 'c006',
    title: '4t冷蔵車ドライバー／東北エリア食品配送',
    employmentType: '正社員',
    salaryMin: 280000,
    salaryMax: 340000,
    salaryType: '月給',
    location: '宮城県仙台市宮城野区',
    requiredLicense: '中型免許',
    vehicleType: '4t',
    isActive: true,
    postedAt: '2026-01-15',
  },
  {
    id: 'j017',
    companyId: 'c006',
    title: '10tドライバー／仙台⇔東京定期便',
    employmentType: '正社員',
    salaryMin: 320000,
    salaryMax: 400000,
    salaryType: '月給',
    location: '宮城県仙台市宮城野区',
    requiredLicense: '大型免許',
    vehicleType: '10t',
    isActive: true,
    postedAt: '2025-10-20',
  },

  // === Standard: c007 首都圏エクスプレス (東京都) — 2 jobs ===
  {
    id: 'j018',
    companyId: 'c007',
    title: '軽貨物ドライバー／即日配送スタッフ',
    employmentType: '業務委託',
    salaryMin: 15000,
    salaryMax: 18000,
    salaryType: '日給',
    location: '東京都墨田区',
    requiredLicense: '普通免許',
    vehicleType: '軽貨物',
    isActive: true,
    postedAt: '2026-03-05',
  },
  {
    id: 'j019',
    companyId: 'c007',
    title: '2tドライバー／都内オフィス機器搬入',
    employmentType: '契約社員',
    salaryMin: 270000,
    salaryMax: 330000,
    salaryType: '月給',
    location: '東京都墨田区',
    requiredLicense: '準中型免許',
    vehicleType: '2t',
    isActive: true,
    postedAt: '2025-11-10',
  },

  // === Standard: c008 北海道物流センター (北海道) — 1 job ===
  {
    id: 'j020',
    companyId: 'c008',
    title: '10t長距離ドライバー／札幌⇔本州便',
    employmentType: '正社員',
    salaryMin: 360000,
    salaryMax: 450000,
    salaryType: '月給',
    location: '北海道札幌市白石区',
    requiredLicense: '大型免許',
    vehicleType: '10t',
    isActive: true,
    postedAt: '2026-02-20',
  },

  // === Standard: c009 四国運輸 (香川県) — 1 job ===
  {
    id: 'j021',
    companyId: 'c009',
    title: '4tドライバー／四国内ルート配送',
    employmentType: '正社員',
    salaryMin: 260000,
    salaryMax: 320000,
    salaryType: '月給',
    location: '香川県高松市',
    requiredLicense: '中型免許',
    vehicleType: '4t',
    isActive: true,
    postedAt: '2025-12-20',
  },

  // === Standard: c010 横浜港運 (神奈川県) — 2 jobs ===
  {
    id: 'j022',
    companyId: 'c010',
    title: '10tトレーラードライバー／港湾コンテナ輸送',
    employmentType: '正社員',
    salaryMin: 370000,
    salaryMax: 440000,
    salaryType: '月給',
    location: '神奈川県横浜市中区',
    requiredLicense: 'けん引免許',
    vehicleType: '10t',
    isActive: true,
    postedAt: '2026-01-25',
  },
  {
    id: 'j023',
    companyId: 'c010',
    title: '4tドライバー／横浜市内建材配送',
    employmentType: '契約社員',
    salaryMin: 280000,
    salaryMax: 350000,
    salaryType: '月給',
    location: '神奈川県横浜市中区',
    requiredLicense: '中型免許',
    vehicleType: '4t',
    isActive: false,
    postedAt: '2025-05-30',
  },

  // === Standard: c011 信州フレッシュ便 (長野県) — 1 job ===
  {
    id: 'j024',
    companyId: 'c011',
    title: '2t冷蔵車ドライバー／信州産青果配送',
    employmentType: '正社員',
    salaryMin: 270000,
    salaryMax: 330000,
    salaryType: '月給',
    location: '長野県長野市',
    requiredLicense: '準中型免許',
    vehicleType: '2t',
    isActive: true,
    postedAt: '2026-02-15',
  },

  // === Standard: c012 広島急送 (広島県) — 2 jobs ===
  {
    id: 'j025',
    companyId: 'c012',
    title: '4tドライバー／中国地方ルート配送',
    employmentType: '正社員',
    salaryMin: 270000,
    salaryMax: 340000,
    salaryType: '月給',
    location: '広島県広島市南区',
    requiredLicense: '中型免許',
    vehicleType: '4t',
    isActive: true,
    postedAt: '2025-11-25',
  },
  {
    id: 'j026',
    companyId: 'c012',
    title: '早朝仕分け・配送助手',
    employmentType: 'アルバイト',
    salaryMin: 1300,
    salaryMax: 1600,
    salaryType: '時給',
    location: '広島県広島市南区',
    requiredLicense: '不要',
    vehicleType: '軽貨物',
    isActive: true,
    postedAt: '2026-03-10',
  },

  // === Standard: c013 沖縄ロジサポート (沖縄県) — 2 jobs ===
  {
    id: 'j027',
    companyId: 'c013',
    title: '軽貨物ドライバー／那覇市内宅配',
    employmentType: '業務委託',
    salaryMin: 10000,
    salaryMax: 14000,
    salaryType: '日給',
    location: '沖縄県那覇市',
    requiredLicense: '普通免許',
    vehicleType: '軽貨物',
    isActive: true,
    postedAt: '2026-02-28',
  },
  {
    id: 'j028',
    companyId: 'c013',
    title: '2tドライバー／離島フェリー積込み・配送',
    employmentType: '正社員',
    salaryMin: 250000,
    salaryMax: 310000,
    salaryType: '月給',
    location: '沖縄県那覇市',
    requiredLicense: '準中型免許',
    vehicleType: '2t',
    isActive: true,
    postedAt: '2025-10-10',
  },
]

/** Returns only active jobs for the given company */
export function getJobsByCompany(companyId: string): Job[] {
  return dummyJobs.filter((job) => job.companyId === companyId && job.isActive)
}
