import type { Review } from '@/types'

export const dummyReviews: Review[] = [
  // ── c001: Premium company (~12 reviews) ──
  {
    id: 'r001',
    companyId: 'c001',
    authorInitials: 'TY',
    rating: 4.8,
    breakdown: { deliveryQuality: 5.0, responseSpeed: 4.5, priceValue: 4.5, communication: 5.0, overall: 4.8 },
    text: '急な依頼にも関わらず、当日中に対応していただきました。ドライバーさんの丁寧な対応にも感謝しています。',
    postedAt: '2026-03-10',
    highlightTags: ['迅速対応', '丁寧'],
  },
  {
    id: 'r002',
    companyId: 'c001',
    authorInitials: 'KS',
    rating: 5.0,
    breakdown: { deliveryQuality: 5.0, responseSpeed: 5.0, priceValue: 4.5, communication: 5.0, overall: 5.0 },
    text: '冷凍品の配送をお願いしましたが、温度管理が完璧でした。定期便としてこれからもお願いしたいです。',
    postedAt: '2026-02-28',
    highlightTags: ['温度管理', '信頼性'],
  },
  {
    id: 'r003',
    companyId: 'c001',
    authorInitials: 'MH',
    rating: 4.5,
    breakdown: { deliveryQuality: 4.5, responseSpeed: 4.0, priceValue: 4.5, communication: 5.0, overall: 4.5 },
    text: '見積もりの段階から非常に分かりやすく、追加料金もなく安心できました。荷物の取り扱いも丁寧です。',
    postedAt: '2026-02-15',
    highlightTags: ['明朗会計', '丁寧'],
  },
  {
    id: 'r004',
    companyId: 'c001',
    authorInitials: 'AN',
    rating: 4.2,
    breakdown: { deliveryQuality: 4.5, responseSpeed: 3.5, priceValue: 4.0, communication: 4.5, overall: 4.2 },
    text: '大型家具の配送でしたが、搬入までしっかり対応してもらえました。少し時間はかかりましたが品質は満足です。',
    postedAt: '2026-01-20',
    highlightTags: ['搬入対応', '品質重視'],
  },
  {
    id: 'r005',
    companyId: 'c001',
    authorInitials: 'RK',
    rating: 4.9,
    breakdown: { deliveryQuality: 5.0, responseSpeed: 5.0, priceValue: 4.5, communication: 5.0, overall: 4.9 },
    text: '何度もリピートしています。毎回安定したサービスで、他社に変える理由がありません。営業担当の方も親切です。',
    postedAt: '2026-01-05',
    highlightTags: ['リピーター', '安定品質'],
  },
  {
    id: 'r006',
    companyId: 'c001',
    authorInitials: 'ST',
    rating: 4.6,
    breakdown: { deliveryQuality: 4.5, responseSpeed: 4.5, priceValue: 4.5, communication: 5.0, overall: 4.6 },
    text: '初めての利用でしたが、手配から配送完了までスムーズでした。報告連絡も細かく安心できます。',
    postedAt: '2025-12-22',
    highlightTags: ['報告連絡', 'スムーズ'],
  },
  {
    id: 'r007',
    companyId: 'c001',
    authorInitials: 'YM',
    rating: 3.8,
    breakdown: { deliveryQuality: 4.0, responseSpeed: 3.5, priceValue: 3.5, communication: 4.0, overall: 3.8 },
    text: '品質は良いのですが、繁忙期の対応が少し遅れました。通常期は問題ありません。',
    postedAt: '2025-12-01',
    highlightTags: ['品質重視'],
  },
  {
    id: 'r008',
    companyId: 'c001',
    authorInitials: 'HT',
    rating: 4.7,
    breakdown: { deliveryQuality: 5.0, responseSpeed: 4.5, priceValue: 4.0, communication: 5.0, overall: 4.7 },
    text: '精密機器の輸送を依頼しましたが、専用の梱包材で完璧に保護していただけました。プロフェッショナルです。',
    postedAt: '2025-11-15',
    highlightTags: ['精密輸送', 'プロ対応'],
  },
  {
    id: 'r009',
    companyId: 'c001',
    authorInitials: 'NK',
    rating: 4.4,
    breakdown: { deliveryQuality: 4.5, responseSpeed: 4.0, priceValue: 4.5, communication: 4.5, overall: 4.4 },
    text: '地方への長距離配送でしたが、予定通りの時間に届けていただきました。追跡システムも便利です。',
    postedAt: '2025-10-28',
    highlightTags: ['長距離対応', '時間厳守'],
  },
  {
    id: 'r010',
    companyId: 'c001',
    authorInitials: 'FW',
    rating: 5.0,
    breakdown: { deliveryQuality: 5.0, responseSpeed: 5.0, priceValue: 5.0, communication: 5.0, overall: 5.0 },
    text: '年末の繁忙期にも関わらず、完璧な対応でした。来年もよろしくお願いします。',
    postedAt: '2025-10-10',
    highlightTags: ['繁忙期対応', '完璧'],
  },
  {
    id: 'r011',
    companyId: 'c001',
    authorInitials: 'DI',
    rating: 4.3,
    breakdown: { deliveryQuality: 4.5, responseSpeed: 4.0, priceValue: 4.0, communication: 4.5, overall: 4.3 },
    text: '複数拠点への配送を一括でお願いできるのが便利です。管理の手間が大幅に減りました。',
    postedAt: '2025-09-18',
    highlightTags: ['一括配送', '効率的'],
  },
  {
    id: 'r012',
    companyId: 'c001',
    authorInitials: 'OT',
    rating: 4.6,
    breakdown: { deliveryQuality: 4.5, responseSpeed: 4.5, priceValue: 4.5, communication: 5.0, overall: 4.6 },
    text: 'ECサイトの出荷業務を委託していますが、クレームがほとんどなくなりました。顧客満足度が上がっています。',
    postedAt: '2025-08-25',
    highlightTags: ['EC対応', '低クレーム率'],
  },

  // ── c002: Premium company (~11 reviews) ──
  {
    id: 'r013',
    companyId: 'c002',
    authorInitials: 'IM',
    rating: 4.7,
    breakdown: { deliveryQuality: 5.0, responseSpeed: 4.5, priceValue: 4.0, communication: 5.0, overall: 4.7 },
    text: '冷蔵品の全国配送をお願いしていますが、温度ログも提供してくれるので安心です。',
    postedAt: '2026-03-15',
    highlightTags: ['温度管理', '全国対応'],
  },
  {
    id: 'r014',
    companyId: 'c002',
    authorInitials: 'WK',
    rating: 4.5,
    breakdown: { deliveryQuality: 4.5, responseSpeed: 4.5, priceValue: 4.0, communication: 4.5, overall: 4.5 },
    text: '10tトラックでの大量輸送を定期的にお願いしています。ドライバーの質が高く信頼できます。',
    postedAt: '2026-03-01',
    highlightTags: ['大型輸送', 'ドライバー品質'],
  },
  {
    id: 'r015',
    companyId: 'c002',
    authorInitials: 'ES',
    rating: 4.9,
    breakdown: { deliveryQuality: 5.0, responseSpeed: 5.0, priceValue: 4.5, communication: 5.0, overall: 4.9 },
    text: '深夜帯の緊急配送に対応していただきました。他社に断られた案件でしたので本当に助かりました。',
    postedAt: '2026-02-10',
    highlightTags: ['緊急対応', '深夜配送'],
  },
  {
    id: 'r016',
    companyId: 'c002',
    authorInitials: 'JT',
    rating: 3.9,
    breakdown: { deliveryQuality: 4.0, responseSpeed: 3.5, priceValue: 3.5, communication: 4.5, overall: 3.9 },
    text: '価格は少し高めですが、サービスの質を考えると妥当だと思います。品質重視の方にはおすすめです。',
    postedAt: '2026-01-25',
    highlightTags: ['品質重視', '高品質'],
  },
  {
    id: 'r017',
    companyId: 'c002',
    authorInitials: 'PL',
    rating: 4.8,
    breakdown: { deliveryQuality: 5.0, responseSpeed: 4.5, priceValue: 4.5, communication: 5.0, overall: 4.8 },
    text: '引越しの荷物配送をお願いしました。時間指定通りに来てくれて、家具も傷一つなく運んでもらえました。',
    postedAt: '2025-12-18',
    highlightTags: ['時間厳守', '丁寧'],
  },
  {
    id: 'r018',
    companyId: 'c002',
    authorInitials: 'GN',
    rating: 4.4,
    breakdown: { deliveryQuality: 4.5, responseSpeed: 4.0, priceValue: 4.5, communication: 4.5, overall: 4.4 },
    text: '建設資材の定期配送で利用しています。現場の状況に合わせて柔軟に対応してくれるのが助かります。',
    postedAt: '2025-11-30',
    highlightTags: ['建設資材', '柔軟対応'],
  },
  {
    id: 'r019',
    companyId: 'c002',
    authorInitials: 'BM',
    rating: 4.6,
    breakdown: { deliveryQuality: 4.5, responseSpeed: 4.5, priceValue: 4.5, communication: 5.0, overall: 4.6 },
    text: '見積もり回答が早く、急ぎの案件でもスピーディに手配してもらえます。レスポンスの良さが魅力です。',
    postedAt: '2025-11-05',
    highlightTags: ['迅速対応', 'レスポンス'],
  },
  {
    id: 'r020',
    companyId: 'c002',
    authorInitials: 'CY',
    rating: 4.1,
    breakdown: { deliveryQuality: 4.0, responseSpeed: 4.0, priceValue: 4.0, communication: 4.5, overall: 4.1 },
    text: '概ね満足していますが、繁忙期は車両の確保が難しいことがあります。早めの予約をおすすめします。',
    postedAt: '2025-10-20',
    highlightTags: ['事前予約推奨'],
  },
  {
    id: 'r021',
    companyId: 'c002',
    authorInitials: 'LH',
    rating: 4.7,
    breakdown: { deliveryQuality: 5.0, responseSpeed: 4.5, priceValue: 4.0, communication: 5.0, overall: 4.7 },
    text: '医薬品の温度管理輸送で利用しています。厳しい基準にもしっかり対応してくれる数少ない業者です。',
    postedAt: '2025-09-28',
    highlightTags: ['医薬品対応', '温度管理'],
  },
  {
    id: 'r022',
    companyId: 'c002',
    authorInitials: 'QA',
    rating: 5.0,
    breakdown: { deliveryQuality: 5.0, responseSpeed: 5.0, priceValue: 5.0, communication: 5.0, overall: 5.0 },
    text: '3年以上のお付き合いですが、一度もトラブルがありません。社内でも評価が非常に高いです。',
    postedAt: '2025-09-10',
    highlightTags: ['長期取引', 'トラブルなし'],
  },
  {
    id: 'r023',
    companyId: 'c002',
    authorInitials: 'VR',
    rating: 4.3,
    breakdown: { deliveryQuality: 4.5, responseSpeed: 4.0, priceValue: 4.0, communication: 4.5, overall: 4.3 },
    text: 'イベント会場への什器搬入をお願いしました。養生もしっかりしていて、会場を傷つけることなく完了しました。',
    postedAt: '2025-08-15',
    highlightTags: ['イベント対応', '養生対応'],
  },

  // ── c003: Premium company (~10 reviews) ──
  {
    id: 'r024',
    companyId: 'c003',
    authorInitials: 'TK',
    rating: 4.6,
    breakdown: { deliveryQuality: 4.5, responseSpeed: 4.5, priceValue: 4.5, communication: 5.0, overall: 4.6 },
    text: '食品工場からスーパーへの定期配送をお願いしています。時間管理が正確で助かっています。',
    postedAt: '2026-03-18',
    highlightTags: ['定期便', '時間厳守'],
  },
  {
    id: 'r025',
    companyId: 'c003',
    authorInitials: 'SM',
    rating: 4.8,
    breakdown: { deliveryQuality: 5.0, responseSpeed: 4.5, priceValue: 4.5, communication: 5.0, overall: 4.8 },
    text: '軽貨物での小口配送を多数依頼していますが、毎回きちんと配達完了の連絡をいただけます。',
    postedAt: '2026-02-22',
    highlightTags: ['小口配送', '報告連絡'],
  },
  {
    id: 'r026',
    companyId: 'c003',
    authorInitials: 'HD',
    rating: 4.2,
    breakdown: { deliveryQuality: 4.5, responseSpeed: 3.5, priceValue: 4.5, communication: 4.0, overall: 4.2 },
    text: 'コスパが良いです。他社と比較して料金が抑えめなのに、サービス品質は遜色ありません。',
    postedAt: '2026-02-05',
    highlightTags: ['コスパ', '料金適正'],
  },
  {
    id: 'r027',
    companyId: 'c003',
    authorInitials: 'KW',
    rating: 4.9,
    breakdown: { deliveryQuality: 5.0, responseSpeed: 5.0, priceValue: 4.5, communication: 5.0, overall: 4.9 },
    text: '台風接近中でも安全を確認しながら配送を完了してくれました。プロ意識の高さに感動しました。',
    postedAt: '2026-01-12',
    highlightTags: ['プロ意識', '安全管理'],
  },
  {
    id: 'r028',
    companyId: 'c003',
    authorInitials: 'NM',
    rating: 3.5,
    breakdown: { deliveryQuality: 3.5, responseSpeed: 3.0, priceValue: 4.0, communication: 3.5, overall: 3.5 },
    text: '一部荷物の到着が30分ほど遅れましたが、事前に連絡があったので対応できました。改善に期待します。',
    postedAt: '2025-12-10',
    highlightTags: ['事前連絡あり'],
  },
  {
    id: 'r029',
    companyId: 'c003',
    authorInitials: 'AK',
    rating: 4.5,
    breakdown: { deliveryQuality: 4.5, responseSpeed: 4.5, priceValue: 4.0, communication: 4.5, overall: 4.5 },
    text: 'ウイング車での配送をお願いしましたが、荷積み・荷降ろしが効率的で作業時間が短縮されました。',
    postedAt: '2025-11-22',
    highlightTags: ['ウイング車', '効率的'],
  },
  {
    id: 'r030',
    companyId: 'c003',
    authorInitials: 'RT',
    rating: 4.7,
    breakdown: { deliveryQuality: 5.0, responseSpeed: 4.5, priceValue: 4.0, communication: 5.0, overall: 4.7 },
    text: '危険物の輸送許可を持っているので、化学品の配送も安心して任せられます。書類対応も迅速です。',
    postedAt: '2025-10-30',
    highlightTags: ['危険物対応', '書類対応'],
  },
  {
    id: 'r031',
    companyId: 'c003',
    authorInitials: 'UF',
    rating: 4.4,
    breakdown: { deliveryQuality: 4.5, responseSpeed: 4.0, priceValue: 4.5, communication: 4.5, overall: 4.4 },
    text: '複数の温度帯の荷物を同時に運んでもらえるのが便利です。仕分けも正確で問題ありません。',
    postedAt: '2025-10-05',
    highlightTags: ['複数温度帯', '正確'],
  },
  {
    id: 'r032',
    companyId: 'c003',
    authorInitials: 'ML',
    rating: 4.0,
    breakdown: { deliveryQuality: 4.0, responseSpeed: 4.0, priceValue: 4.0, communication: 4.0, overall: 4.0 },
    text: '標準的なサービスですが、安定しているのが一番大事だと思います。大きな問題は一度もありません。',
    postedAt: '2025-09-15',
    highlightTags: ['安定品質'],
  },
  {
    id: 'r033',
    companyId: 'c003',
    authorInitials: 'YH',
    rating: 4.8,
    breakdown: { deliveryQuality: 5.0, responseSpeed: 4.5, priceValue: 4.5, communication: 5.0, overall: 4.8 },
    text: '展示会の什器搬出入をお願いしました。タイトなスケジュールでしたが、完璧に対応していただけました。',
    postedAt: '2025-08-20',
    highlightTags: ['展示会対応', 'スケジュール管理'],
  },

  // ── c004: Standard company (~5 reviews) ──
  {
    id: 'r034',
    companyId: 'c004',
    authorInitials: 'KI',
    rating: 4.3,
    breakdown: { deliveryQuality: 4.5, responseSpeed: 4.0, priceValue: 4.0, communication: 4.5, overall: 4.3 },
    text: '関東エリアの配送に強く、当日便でも対応してもらえました。地域密着型で頼りになります。',
    postedAt: '2026-03-05',
    highlightTags: ['関東エリア', '当日便'],
  },
  {
    id: 'r035',
    companyId: 'c004',
    authorInitials: 'OY',
    rating: 4.0,
    breakdown: { deliveryQuality: 4.0, responseSpeed: 4.0, priceValue: 4.0, communication: 4.0, overall: 4.0 },
    text: '2tトラックでの市内配送を月に数回利用しています。料金も手頃で使いやすいです。',
    postedAt: '2026-01-30',
    highlightTags: ['市内配送', '手頃な料金'],
  },
  {
    id: 'r036',
    companyId: 'c004',
    authorInitials: 'TS',
    rating: 3.7,
    breakdown: { deliveryQuality: 3.5, responseSpeed: 3.5, priceValue: 4.0, communication: 4.0, overall: 3.7 },
    text: '価格面では満足していますが、配送状況の連絡がもう少し欲しいところです。',
    postedAt: '2025-12-15',
    highlightTags: ['料金適正'],
  },
  {
    id: 'r037',
    companyId: 'c004',
    authorInitials: 'MK',
    rating: 4.5,
    breakdown: { deliveryQuality: 4.5, responseSpeed: 4.5, priceValue: 4.0, communication: 4.5, overall: 4.5 },
    text: '雨の日の配送でしたが、荷物が濡れないようにしっかりカバーしてくれていました。気配りに感謝です。',
    postedAt: '2025-11-08',
    highlightTags: ['気配り', '丁寧'],
  },
  {
    id: 'r038',
    companyId: 'c004',
    authorInitials: 'HN',
    rating: 4.1,
    breakdown: { deliveryQuality: 4.0, responseSpeed: 4.0, priceValue: 4.5, communication: 4.0, overall: 4.1 },
    text: '小さい会社ですが、その分融通が利いて助かります。急な変更にも対応してくれました。',
    postedAt: '2025-09-25',
    highlightTags: ['柔軟対応', '融通'],
  },

  // ── c005: Standard company (~4 reviews) ──
  {
    id: 'r039',
    companyId: 'c005',
    authorInitials: 'SK',
    rating: 4.6,
    breakdown: { deliveryQuality: 4.5, responseSpeed: 4.5, priceValue: 4.5, communication: 5.0, overall: 4.6 },
    text: '冷凍食品の配送を専門的に扱っているだけあって、温度管理が徹底されています。',
    postedAt: '2026-02-20',
    highlightTags: ['冷凍専門', '温度管理'],
  },
  {
    id: 'r040',
    companyId: 'c005',
    authorInitials: 'YT',
    rating: 4.2,
    breakdown: { deliveryQuality: 4.5, responseSpeed: 4.0, priceValue: 3.5, communication: 4.5, overall: 4.2 },
    text: '品質は申し分ないのですが、冷凍便は少し割高に感じます。ただし品質を考えれば納得できます。',
    postedAt: '2025-12-28',
    highlightTags: ['品質重視', '冷凍便'],
  },
  {
    id: 'r041',
    companyId: 'c005',
    authorInitials: 'NG',
    rating: 4.8,
    breakdown: { deliveryQuality: 5.0, responseSpeed: 4.5, priceValue: 4.5, communication: 5.0, overall: 4.8 },
    text: 'お歳暮シーズンの大量配送をお願いしましたが、一件も遅延なく完了しました。素晴らしいです。',
    postedAt: '2025-11-18',
    highlightTags: ['大量配送', '遅延なし'],
  },
  {
    id: 'r042',
    companyId: 'c005',
    authorInitials: 'FH',
    rating: 3.8,
    breakdown: { deliveryQuality: 4.0, responseSpeed: 3.5, priceValue: 3.5, communication: 4.0, overall: 3.8 },
    text: '週末の配送に対応してくれるのが助かります。ただ、土日は少し対応が遅くなることがあります。',
    postedAt: '2025-10-12',
    highlightTags: ['週末対応'],
  },

  // ── c006: Standard company (~4 reviews) ──
  {
    id: 'r043',
    companyId: 'c006',
    authorInitials: 'DR',
    rating: 4.4,
    breakdown: { deliveryQuality: 4.5, responseSpeed: 4.0, priceValue: 4.5, communication: 4.5, overall: 4.4 },
    text: '工場間の部品輸送で利用しています。ジャストインタイム配送にしっかり対応してくれます。',
    postedAt: '2026-03-08',
    highlightTags: ['JIT配送', '工場間輸送'],
  },
  {
    id: 'r044',
    companyId: 'c006',
    authorInitials: 'KA',
    rating: 4.0,
    breakdown: { deliveryQuality: 4.0, responseSpeed: 4.0, priceValue: 4.0, communication: 4.0, overall: 4.0 },
    text: '可もなく不可もなく、安定したサービスです。長期契約で割引があるのも嬉しいポイントです。',
    postedAt: '2026-01-15',
    highlightTags: ['安定品質', '長期割引'],
  },
  {
    id: 'r045',
    companyId: 'c006',
    authorInitials: 'WS',
    rating: 4.7,
    breakdown: { deliveryQuality: 5.0, responseSpeed: 4.5, priceValue: 4.0, communication: 5.0, overall: 4.7 },
    text: '引越し後の不用品回収まで対応してくれました。ワンストップで助かりました。',
    postedAt: '2025-11-25',
    highlightTags: ['ワンストップ', '回収対応'],
  },
  {
    id: 'r046',
    companyId: 'c006',
    authorInitials: 'PT',
    rating: 3.6,
    breakdown: { deliveryQuality: 3.5, responseSpeed: 3.5, priceValue: 4.0, communication: 3.5, overall: 3.6 },
    text: '配送先を間違えそうになったことがありましたが、すぐに気づいて修正してくれました。ヒヤリとしました。',
    postedAt: '2025-10-08',
    highlightTags: ['改善余地あり'],
  },

  // ── c007: Standard company (~4 reviews) ──
  {
    id: 'r047',
    companyId: 'c007',
    authorInitials: 'JM',
    rating: 4.5,
    breakdown: { deliveryQuality: 4.5, responseSpeed: 4.5, priceValue: 4.0, communication: 4.5, overall: 4.5 },
    text: '大阪を拠点に関西一円をカバーしてくれます。地理に詳しく、最適なルートで配送してくれます。',
    postedAt: '2026-02-12',
    highlightTags: ['関西エリア', 'ルート最適化'],
  },
  {
    id: 'r048',
    companyId: 'c007',
    authorInitials: 'RN',
    rating: 4.1,
    breakdown: { deliveryQuality: 4.0, responseSpeed: 4.0, priceValue: 4.0, communication: 4.5, overall: 4.1 },
    text: '飲食店への食材配送で利用しています。朝早い時間帯にも対応してくれるのが助かります。',
    postedAt: '2025-12-20',
    highlightTags: ['早朝配送', '食材配送'],
  },
  {
    id: 'r049',
    companyId: 'c007',
    authorInitials: 'GK',
    rating: 3.9,
    breakdown: { deliveryQuality: 4.0, responseSpeed: 3.5, priceValue: 4.0, communication: 4.0, overall: 3.9 },
    text: '通常は問題ないのですが、年末年始の車両確保が難しかったです。繁忙期は早めの相談が必要です。',
    postedAt: '2025-10-25',
    highlightTags: ['繁忙期注意'],
  },
  {
    id: 'r050',
    companyId: 'c007',
    authorInitials: 'EK',
    rating: 4.3,
    breakdown: { deliveryQuality: 4.5, responseSpeed: 4.0, priceValue: 4.0, communication: 4.5, overall: 4.3 },
    text: 'ドライバーさんがいつも元気で気持ちがいいです。荷受け先からも評判がいいと聞いています。',
    postedAt: '2025-09-05',
    highlightTags: ['ドライバー品質', '好印象'],
  },

  // ── c008: Standard company (~3 reviews) ──
  {
    id: 'r051',
    companyId: 'c008',
    authorInitials: 'BT',
    rating: 4.2,
    breakdown: { deliveryQuality: 4.0, responseSpeed: 4.5, priceValue: 4.0, communication: 4.0, overall: 4.2 },
    text: '見積もり回答が翌日には届くので、急ぎの案件でも助かります。フットワークが軽い会社です。',
    postedAt: '2026-01-28',
    highlightTags: ['見積もり迅速', 'フットワーク'],
  },
  {
    id: 'r052',
    companyId: 'c008',
    authorInitials: 'CH',
    rating: 3.5,
    breakdown: { deliveryQuality: 3.5, responseSpeed: 3.5, priceValue: 3.5, communication: 3.5, overall: 3.5 },
    text: '普通のサービスです。特に不満はありませんが、特筆すべき点もありません。',
    postedAt: '2025-11-10',
    highlightTags: ['標準的'],
  },
  {
    id: 'r053',
    companyId: 'c008',
    authorInitials: 'ZW',
    rating: 4.6,
    breakdown: { deliveryQuality: 4.5, responseSpeed: 4.5, priceValue: 4.5, communication: 5.0, overall: 4.6 },
    text: '担当者が荷物の特性をよく理解してくれていて、適切な車両を提案してくれます。知識が豊富です。',
    postedAt: '2025-09-20',
    highlightTags: ['提案力', '知識豊富'],
  },

  // ── c009: Standard company (~3 reviews) ──
  {
    id: 'r054',
    companyId: 'c009',
    authorInitials: 'TN',
    rating: 4.4,
    breakdown: { deliveryQuality: 4.5, responseSpeed: 4.0, priceValue: 4.5, communication: 4.5, overall: 4.4 },
    text: '名古屋エリアでは一番お世話になっています。地元のネットワークが強く、きめ細かい対応が魅力です。',
    postedAt: '2026-02-18',
    highlightTags: ['名古屋エリア', 'きめ細かい'],
  },
  {
    id: 'r055',
    companyId: 'c009',
    authorInitials: 'HK',
    rating: 4.0,
    breakdown: { deliveryQuality: 4.0, responseSpeed: 4.0, priceValue: 4.0, communication: 4.0, overall: 4.0 },
    text: '中部エリアのルート配送を任せています。ルート設計の提案もしてくれて助かっています。',
    postedAt: '2025-12-05',
    highlightTags: ['ルート配送', '提案力'],
  },
  {
    id: 'r056',
    companyId: 'c009',
    authorInitials: 'YA',
    rating: 4.7,
    breakdown: { deliveryQuality: 5.0, responseSpeed: 4.5, priceValue: 4.0, communication: 5.0, overall: 4.7 },
    text: '精密部品の輸送で振動対策もしっかりしてもらいました。技術的な知識があるドライバーさんでした。',
    postedAt: '2025-10-15',
    highlightTags: ['精密輸送', '振動対策'],
  },

  // ── c010: Standard company (~3 reviews) ──
  {
    id: 'r057',
    companyId: 'c010',
    authorInitials: 'RI',
    rating: 4.1,
    breakdown: { deliveryQuality: 4.0, responseSpeed: 4.0, priceValue: 4.5, communication: 4.0, overall: 4.1 },
    text: '小ロットでも嫌な顔一つせず受けてくれます。個人事業主にも優しい対応が嬉しいです。',
    postedAt: '2026-03-12',
    highlightTags: ['小ロット対応', '親切'],
  },
  {
    id: 'r058',
    companyId: 'c010',
    authorInitials: 'MA',
    rating: 3.8,
    breakdown: { deliveryQuality: 4.0, responseSpeed: 3.5, priceValue: 4.0, communication: 3.5, overall: 3.8 },
    text: '電話対応は少し事務的ですが、配送自体は問題ありません。メールでのやり取りがスムーズです。',
    postedAt: '2025-11-28',
    highlightTags: ['メール対応'],
  },
  {
    id: 'r059',
    companyId: 'c010',
    authorInitials: 'KN',
    rating: 4.5,
    breakdown: { deliveryQuality: 4.5, responseSpeed: 4.5, priceValue: 4.0, communication: 4.5, overall: 4.5 },
    text: 'オフィス移転の際にお世話になりました。養生から復旧まで一貫して対応いただき助かりました。',
    postedAt: '2025-09-30',
    highlightTags: ['オフィス移転', '一貫対応'],
  },

  // ── c011: Standard company (~3 reviews) ──
  {
    id: 'r060',
    companyId: 'c011',
    authorInitials: 'SN',
    rating: 4.3,
    breakdown: { deliveryQuality: 4.5, responseSpeed: 4.0, priceValue: 4.0, communication: 4.5, overall: 4.3 },
    text: '北海道からの農産物の輸送をお願いしています。鮮度を保ったまま届けてくれるので信頼しています。',
    postedAt: '2026-02-08',
    highlightTags: ['農産物', '鮮度管理'],
  },
  {
    id: 'r061',
    companyId: 'c011',
    authorInitials: 'FM',
    rating: 4.0,
    breakdown: { deliveryQuality: 4.0, responseSpeed: 3.5, priceValue: 4.5, communication: 4.0, overall: 4.0 },
    text: '長距離でもリーズナブルな料金設定が魅力です。到着日の連絡もきちんとしてくれます。',
    postedAt: '2025-12-12',
    highlightTags: ['長距離', 'リーズナブル'],
  },
  {
    id: 'r062',
    companyId: 'c011',
    authorInitials: 'WN',
    rating: 3.6,
    breakdown: { deliveryQuality: 3.5, responseSpeed: 3.5, priceValue: 4.0, communication: 3.5, overall: 3.6 },
    text: '冬場の雪の影響で遅延がありましたが、天候要因なので仕方ないと思います。事前連絡はありました。',
    postedAt: '2025-10-02',
    highlightTags: ['天候注意'],
  },

  // ── c012: Standard company (~3 reviews) ──
  {
    id: 'r063',
    companyId: 'c012',
    authorInitials: 'IT',
    rating: 4.5,
    breakdown: { deliveryQuality: 4.5, responseSpeed: 4.5, priceValue: 4.5, communication: 4.5, overall: 4.5 },
    text: '九州エリアの配送はここに任せています。地場の道路事情に詳しくて渋滞を避けてくれます。',
    postedAt: '2026-01-22',
    highlightTags: ['九州エリア', '土地勘'],
  },
  {
    id: 'r064',
    companyId: 'c012',
    authorInitials: 'OE',
    rating: 4.2,
    breakdown: { deliveryQuality: 4.0, responseSpeed: 4.5, priceValue: 4.0, communication: 4.0, overall: 4.2 },
    text: '急な増車にも対応してもらえました。協力会社のネットワークが広いようです。',
    postedAt: '2025-11-15',
    highlightTags: ['増車対応', 'ネットワーク'],
  },
  {
    id: 'r065',
    companyId: 'c012',
    authorInitials: 'VP',
    rating: 3.9,
    breakdown: { deliveryQuality: 4.0, responseSpeed: 3.5, priceValue: 4.0, communication: 4.0, overall: 3.9 },
    text: '請求書の内訳がもう少し詳しいと助かります。配送サービス自体には満足しています。',
    postedAt: '2025-08-30',
    highlightTags: ['請求書改善希望'],
  },

  // ── c013: Standard company (~3 reviews) ──
  {
    id: 'r066',
    companyId: 'c013',
    authorInitials: 'UY',
    rating: 4.6,
    breakdown: { deliveryQuality: 4.5, responseSpeed: 4.5, priceValue: 4.5, communication: 5.0, overall: 4.6 },
    text: 'アパレルの店舗間移動をお願いしました。ハンガーラックごと運んでくれるので助かります。',
    postedAt: '2026-03-01',
    highlightTags: ['アパレル対応', 'ハンガー便'],
  },
  {
    id: 'r067',
    companyId: 'c013',
    authorInitials: 'LT',
    rating: 4.0,
    breakdown: { deliveryQuality: 4.0, responseSpeed: 4.0, priceValue: 4.0, communication: 4.0, overall: 4.0 },
    text: '百貨店への納品で時間指定が厳しいのですが、毎回きちんと間に合わせてくれます。',
    postedAt: '2025-12-18',
    highlightTags: ['時間厳守', '百貨店納品'],
  },
  {
    id: 'r068',
    companyId: 'c013',
    authorInitials: 'QM',
    rating: 4.3,
    breakdown: { deliveryQuality: 4.5, responseSpeed: 4.0, priceValue: 4.0, communication: 4.5, overall: 4.3 },
    text: 'シーズン切り替えの際の大量配送もスムーズに対応いただけました。物流の相談にも乗ってくれます。',
    postedAt: '2025-09-22',
    highlightTags: ['大量配送', '相談対応'],
  },

  // ── c014: Free company (~2 reviews) ──
  {
    id: 'r069',
    companyId: 'c014',
    authorInitials: 'NY',
    rating: 4.0,
    breakdown: { deliveryQuality: 4.0, responseSpeed: 3.5, priceValue: 4.5, communication: 4.0, overall: 4.0 },
    text: '個人経営ですが、丁寧な対応で好感が持てました。小さな荷物の配送にぴったりです。',
    postedAt: '2026-01-10',
    highlightTags: ['個人経営', '丁寧'],
  },
  {
    id: 'r070',
    companyId: 'c014',
    authorInitials: 'HA',
    rating: 3.5,
    breakdown: { deliveryQuality: 3.5, responseSpeed: 3.0, priceValue: 4.0, communication: 3.5, overall: 3.5 },
    text: '料金が安いのは魅力ですが、対応できるエリアが限られています。都内なら問題ないです。',
    postedAt: '2025-10-18',
    highlightTags: ['低価格', 'エリア限定'],
  },

  // ── c015: Free company (~2 reviews) ──
  {
    id: 'r071',
    companyId: 'c015',
    authorInitials: 'KR',
    rating: 3.8,
    breakdown: { deliveryQuality: 4.0, responseSpeed: 3.5, priceValue: 4.0, communication: 3.5, overall: 3.8 },
    text: '軽貨物での近距離配送を何度かお願いしました。真面目な方で、荷物の扱いも丁寧です。',
    postedAt: '2026-02-25',
    highlightTags: ['軽貨物', '近距離'],
  },
  {
    id: 'r072',
    companyId: 'c015',
    authorInitials: 'EM',
    rating: 3.2,
    breakdown: { deliveryQuality: 3.0, responseSpeed: 3.0, priceValue: 3.5, communication: 3.0, overall: 3.2 },
    text: '連絡がつきにくいことがありました。配送自体は問題なかったので、連絡体制の改善を期待します。',
    postedAt: '2025-11-02',
    highlightTags: ['連絡改善希望'],
  },

  // ── c016: Free company (~1 review) ──
  {
    id: 'r073',
    companyId: 'c016',
    authorInitials: 'AD',
    rating: 4.2,
    breakdown: { deliveryQuality: 4.0, responseSpeed: 4.0, priceValue: 4.5, communication: 4.0, overall: 4.2 },
    text: '新しい会社ですが、対応が迅速で印象が良かったです。これからの成長に期待しています。',
    postedAt: '2026-03-20',
    highlightTags: ['新規参入', '迅速対応'],
  },

  // ── c017: Free company (~1 review) ──
  {
    id: 'r074',
    companyId: 'c017',
    authorInitials: 'TO',
    rating: 3.0,
    breakdown: { deliveryQuality: 3.0, responseSpeed: 3.0, priceValue: 3.0, communication: 3.0, overall: 3.0 },
    text: '最低限のサービスは提供してくれますが、まだ経験が浅い印象です。料金は安いので割り切って利用しています。',
    postedAt: '2025-12-25',
    highlightTags: ['低価格', '経験浅め'],
  },
]

/**
 * Returns reviews for a given company, sorted by most recent first.
 */
export function getReviewsByCompany(companyId: string, limit = 5): Review[] {
  return dummyReviews
    .filter((r) => r.companyId === companyId)
    .sort((a, b) => new Date(b.postedAt).getTime() - new Date(a.postedAt).getTime())
    .slice(0, limit)
}
